# Get a list of L4-L7 Services Templates (iApps)
#

- name: URL request
  hosts: localhost
  tasks:
    - name: Get the templates
      uri:
        url: https://10.0.0.167/mgmt/tm/cloud/templates/iapp/
        validate_certs: no
        user: admin
        password: admin
        return_content: yes
      register: iapps_list

    - name: print iapps_list
      debug: msg={{iapps_list}}
#      debug: msg={{iapps_list["items"]["appsvcs_integration_v1.0_001"]}}

    - name: Check response
      debug: msg="Directory is empty"
      when: "'appsvcs_integration_v1.0_001' not in iapps_list"
